### PR TITLE
Facet layouts

### LINKED ISSUE #1: Axes and titles occasionally break facet layouts
When `plot` draws an axis or title that shrinks the size of the overall plot (so some of the text overlaps on the top or bottom), the resulting output is shifted in an undesirable way. Ideally, all of these plots would be lined up programmatically. This is closely related to https://github.com/racket/plot/issues/7.

**Offenders:**
`graphite-examples/fig-44.rkt`:
Screenshot from 2021-06-08 14-41-44
Note that the leftmost plot is shifted compared to the right, and has a different plot area.

`graphite-examples/facet-grid.rkt`
Screenshot from 2021-06-08 14-43-20
This is a particularly egregious example.

### PR DESCRIPTION
**Pull request by ralsei**
Closes #1. See that issue for more details.

This implements a fix for the dreaded facet-axis bug by implementing our own titles and axis labels. This also provides a framework for being able to solve #4 (as it requires left-labels).

Caveats:
- Titles are not centered on the axes. I'm not sure if this is possible, because once pict combiners are used to create a facet plot, we lose plot-metrics and therefore cannot determine where the plot is. Maybe a pict finder metric would be useful here, or just adding pict finders for the internal plot. I would prefer this be fixed before I mark this PR as ready for review.
- `#:width` and `#:height` still are not accurate for facets. This bug was present before the change as well. I'm going to make a solid attempt at solving this before marking this ready for review, but no guarantees whatsoever.

### CODE REVIEW

**Comment by samth** [comment]
I think just remembering the underlying plots and using something like `ct-find` to put things above the center of them should work.

**Comment by ralsei** [comment]
I don't know if using that pict-finder would retain the underlying `plot-pict%` though. I'll test that later.

**Comment by samth** [comment]
I'm not sure I understand. `ct-find` doesn't produce a pict, it takes a pict. You have to remember the underlying pict in the code using `ct-find` and friends.

If the question is whether `vl-append` retains the underlying `plot-pict%` then the answer is definitely yes.

**Comment by ralsei** [comment]
:pray:

**Pull request merged**
